spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: subscriber-news


  gemini:
    secretKey: ${SECRET_KEY}


  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.H2Dialect
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SECRET_EMAIL}
    password: ${SECRET_EMAIL_KEY}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true



